# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Create Release with maven


on:
  push:
    branches:
    - master
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 14
      uses: actions/setup-java@v3
      with:
        java-version: '14'
        distribution: 'adopt'
        cache: maven
      env:
        MAVEN_S3_KEY: ${{ secrets.MAVEN_S3_KEY  }}
        MAVEN_S3_SECRET: ${{ secrets.MAVEN_S3_SECRET  }}
        MAVEN_S3_REGION: 'us-west-2'     
    - name: Build with Maven
      working-directory: ./SilaSDK
      run: mvn --settings settings.xml --file pom.xml -B release:clean release:prepare release:perform
